name: "Deploy Jekyll Site to Pages"

on:
  workflow_run:
    workflows: ["Build Jekyll Site to Pages"]
    types:
      - completed

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download site artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
