name: "Deploy Jekyll Site to Pages"

on:
  workflow_run:
    workflows: ["Build Jekyll Site to Pages"]  # Use the exact name of your build workflow
    types:
      - completed

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download site artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: site-artifact

      - name: Move artifact contents to workspace root
        run: |
          # Use rsync to copy files from site-artifact to the current directory
          rsync -a --remove-source-files site-artifact/ .
          echo "Workspace root after moving artifact:"
          ls -la

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          directory: "."
