name: "Build and Deploy with GitHub Pages"

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Install Dependencies
        run: bundle install

      - name: Build Jekyll Site
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Debug _site directory
        run: ls -la _site

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v1
        # or v2 if available

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
