name: "Build and Deploy Jekyll"

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Install Dependencies
        run: bundle install

      - name: Build Jekyll Site
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Debug _site directory
        run: ls -la _site

      # 1) Upload site artifact (non-deprecated action)
      - name: Upload site
        uses: actions/upload-artifact@v4
        with:
          name: github-pages     # Must match the download step
          path: _site

      # 2) Download the same artifact (even though it's the same job,
      #    this ensures we’re using actions/upload-artifact@v4).
      - name: Download site
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: site-artifact

      - name: Debug downloaded artifact
        run: ls -la site-artifact

      # 3) Move everything from 'site-artifact' into the root of the workspace
      - name: Move Site to Root
        shell: bash
        run: |
          rsync -a --remove-source-files site-artifact/ .
          echo "Workspace root contents after rsync:"
          ls -la


      # 4) Deploy from the current directory
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          directory: "."
