name: "Build and Deploy Jekyll"

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Install Dependencies
        run: bundle install

      - name: Build Jekyll Site
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Debug _site directory
        run: ls -la _site

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages      # Must match download
          path: _site

  deploy:
    needs: build                  # Wait for build job to finish
    runs-on: ubuntu-22.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages     # Must match upload
          path: site-artifact   # Download into a subfolder

      - name: Debug downloaded artifact
        run: ls -la site-artifact

      - name: Move Site to Root
        # Move everything from 'site-artifact/' to '.'
        # so that deploy-pages@v2 finds index.html, etc.
        shell: bash
        run: |
          shopt -s dotglob
          mv site-artifact/* .

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
